services:
  db:
    container_name: tennis-scoreboard-db
    image: postgres:16-alpine
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "4680:5432"

  tennis-scoreboard:
    container_name: tennis-scoreboard-app
    image: asalavei/tennis-scoreboard
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "80:8080"